apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - image:  harbor.nexonera.io/flaskapp/flaskapp:v1
          name: flaskapp
          ports:
            - containerPort: 5000
